plugin:
  name: custom-data-type-location
  version: 1.0
  server:
    api-version:
      require: 1
  webfrontend:
    url: custom-data-type-location.js
    css: custom-data-type-location.css
    l10n: l10n/

custom_types:
  location:
    update:
      script: build/scripts/location-update.js
      batch_size: 1000
    mapping:
      displayName:
        type: text_l10n
    config:
      schema:
        - name: type
          parameters:
            value:
              type: select
              options: ["latitude_and_longitude"]